{
  description = "Android development environment";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
    android-nixpkgs = {
      url = "github:tadfisher/android-nixpkgs";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    zig-overlay = {
      url = "github:mitchellh/zig-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = {
    nixpkgs,
    flake-utils,
    android-nixpkgs,
    zig-overlay,
    ...
  }:
    let
      localAndroidSdkRoot = builtins.getEnv "TERMUX_LOCAL_ANDROID_SDK";
      useLocalAndroidSdk = localAndroidSdkRoot != "";

      allSystems = [
        "x86_64-linux"
        "x86_64-darwin"
        "aarch64-darwin"
      ];

      forAllSystems = f:
        nixpkgs.lib.genAttrs allSystems (system:
          let
            pkgs = import nixpkgs {
              inherit system;
              config.allowUnfree = true;
              overlays = [ zig-overlay.overlays.default ];
            };
            androidSdk = android-nixpkgs.sdk.${system} (sdkPkgs: with sdkPkgs; [
              cmdline-tools-latest
              platform-tools
              build-tools-35-0-0
              build-tools-36-0-0
              platforms-android-28
              platforms-android-35
              platforms-android-36
              platforms-android-37-0
              ndk-29-0-14206865
              cmake-3-22-1
              emulator
              system-images-android-34-google-apis-arm64-v8a
            ]);
          in
            f {
              inherit pkgs androidSdk;
              androidSdkRoot =
                if useLocalAndroidSdk
                then localAndroidSdkRoot
                else "${androidSdk}/share/android-sdk";
            });
    in {
      devShells = forAllSystems ({ pkgs, androidSdk, androidSdkRoot }: {
        default = (if useLocalAndroidSdk then pkgs.mkShellNoCC else pkgs.mkShell) {
          packages = pkgs.lib.optionals (!useLocalAndroidSdk) (with pkgs; [
            jdk17
            androidSdk
            zigpkgs."0.16.0"
          ]);

          JAVA_HOME = if useLocalAndroidSdk then "" else pkgs.jdk17.home;

          shellHook = ''
            unset ANDROID_PREFS_ROOT

            if [ "$(uname -s)" = "Darwin" ] && [ -z "''${DEVELOPER_DIR+x}" ]; then
              active_developer_dir="$(xcode-select -p 2>/dev/null || true)"
              if [ "$active_developer_dir" = "/Library/Developer/CommandLineTools" ]; then
                if [ -n "''${ZIG_0_16_0_DEVELOPER_DIR:-}" ]; then
                  export DEVELOPER_DIR="$ZIG_0_16_0_DEVELOPER_DIR"
                fi
              fi
            fi

            profileJava="$(readlink -f "$HOME/.nix-profile/bin/java" 2>/dev/null || true)"
            if [ -n "$profileJava" ]; then
              export JAVA_HOME="$(printf '%s' "$profileJava" | sed 's#/bin/java$##')"
            fi

            export NIX_ANDROID_SDK_ROOT="${androidSdkRoot}"
            export TERMUX_ANDROID_SDK_ROOT="$PWD/.android-sdk"
            export TERMUX_ANDROID_SDK_ROOT_FILE="$PWD/.android-sdk-root"

            previousAndroidSdkRoot=""
            if [ -f "$TERMUX_ANDROID_SDK_ROOT_FILE" ]; then
              previousAndroidSdkRoot="$(cat "$TERMUX_ANDROID_SDK_ROOT_FILE")"
            fi

            if [ ! -L "$TERMUX_ANDROID_SDK_ROOT" ] || [ "$(readlink "$TERMUX_ANDROID_SDK_ROOT" 2>/dev/null || true)" != "$NIX_ANDROID_SDK_ROOT" ]; then
              rm -rf "$TERMUX_ANDROID_SDK_ROOT"
              ln -s "$NIX_ANDROID_SDK_ROOT" "$TERMUX_ANDROID_SDK_ROOT"
            fi

            if [ "$previousAndroidSdkRoot" != "$NIX_ANDROID_SDK_ROOT" ]; then
              find . -type d \( -path './*/build/.cxx' -o -path './*/build/intermediates/cxx' \) -prune -exec rm -rf {} +
              printf '%s\n' "$NIX_ANDROID_SDK_ROOT" > "$TERMUX_ANDROID_SDK_ROOT_FILE"
            fi

            export ANDROID_HOME="$TERMUX_ANDROID_SDK_ROOT"
            export ANDROID_SDK_ROOT="$ANDROID_HOME"
            export ANDROID_NDK_HOME="$ANDROID_HOME/ndk/29.0.14206865"
            export ANDROID_USER_HOME="$PWD/.android"

            if [ -x "$HOME/.nix-profile/bin/zig" ] && [ "$("$HOME/.nix-profile/bin/zig" version 2>/dev/null || true)" = "0.16.0" ]; then
              export ZIG_EXECUTABLE="$HOME/.nix-profile/bin/zig"
              export ZIG_0_16_0_EXECUTABLE="$ZIG_EXECUTABLE"
            fi

            mkdir -p "$ANDROID_USER_HOME"

            if [ -f local.properties ]; then
              chmod u+w local.properties 2>/dev/null || true
            fi

            printf '%s\n' \
              '# Generated by `nix develop`.' \
              '# This file is ignored by git.' \
              "sdk.dir=$ANDROID_HOME" \
              > local.properties
          '';
        };
      });
    };
}
