{
  description = "Android development environment";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
    android-nixpkgs = {
      url = "github:tadfisher/android-nixpkgs";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    zig-overlay = {
      url = "github:mitchellh/zig-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = {
    nixpkgs,
    flake-utils,
    android-nixpkgs,
    zig-overlay,
    ...
  }:
    let
      allSystems = [
        "x86_64-linux"
        "x86_64-darwin"
        "aarch64-darwin"
      ];

      forAllSystems = f:
        nixpkgs.lib.genAttrs allSystems (system:
          f {
            pkgs = import nixpkgs {
              inherit system;
              config.allowUnfree = true;
              overlays = [ zig-overlay.overlays.default ];
            };

            androidSdk = android-nixpkgs.sdk.${system} (sdkPkgs: with sdkPkgs; [
              cmdline-tools-latest
              platform-tools
              build-tools-35-0-0
              build-tools-36-0-0
              platforms-android-28
              platforms-android-35
              platforms-android-36
              ndk-29-0-14206865
              cmake-3-22-1
            ]);
          });
    in {
      devShells = forAllSystems ({ pkgs, androidSdk }: {
        default = pkgs.mkShell {
          packages = with pkgs; [
            jdk17
            androidSdk
            zigpkgs."0.15.2"
          ];

          JAVA_HOME = pkgs.jdk17.home;

          shellHook = ''
            unset ANDROID_PREFS_ROOT

            export NIX_ANDROID_SDK_ROOT="${androidSdk}/share/android-sdk"
            export TERMUX_ANDROID_SDK_ROOT="$PWD/.android-sdk"
            export TERMUX_ANDROID_SDK_ROOT_FILE="$PWD/.android-sdk-root"

            previousAndroidSdkRoot=""
            if [ -f "$TERMUX_ANDROID_SDK_ROOT_FILE" ]; then
              previousAndroidSdkRoot="$(cat "$TERMUX_ANDROID_SDK_ROOT_FILE")"
            fi

            if [ ! -L "$TERMUX_ANDROID_SDK_ROOT" ] || [ "$(readlink "$TERMUX_ANDROID_SDK_ROOT" 2>/dev/null || true)" != "$NIX_ANDROID_SDK_ROOT" ]; then
              rm -rf "$TERMUX_ANDROID_SDK_ROOT"
              ln -s "$NIX_ANDROID_SDK_ROOT" "$TERMUX_ANDROID_SDK_ROOT"
            fi

            if [ "$previousAndroidSdkRoot" != "$NIX_ANDROID_SDK_ROOT" ]; then
              find . -type d \( -path './*/build/.cxx' -o -path './*/build/intermediates/cxx' \) -prune -exec rm -rf {} +
              printf '%s\n' "$NIX_ANDROID_SDK_ROOT" > "$TERMUX_ANDROID_SDK_ROOT_FILE"
            fi

            export ANDROID_HOME="$TERMUX_ANDROID_SDK_ROOT"
            export ANDROID_SDK_ROOT="$ANDROID_HOME"
            export ANDROID_NDK_HOME="$ANDROID_HOME/ndk/29.0.14206865"
            export ANDROID_USER_HOME="$PWD/.android"

            mkdir -p "$ANDROID_USER_HOME"

            if [ -f local.properties ]; then
              chmod u+w local.properties 2>/dev/null || true
            fi

            printf '%s\n' \
              '# Generated by `nix develop`.' \
              '# This file is ignored by git.' \
              "sdk.dir=$ANDROID_HOME" \
              > local.properties
          '';
        };
      });
    };
}
