name: Unit tests

on:
  push:
    branches:
      - master
      - android-10
  pull_request:
    branches:
      - master
      - android-10

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v6
    - name: Install Determinate Nix
      uses: DeterminateSystems/determinate-nix-action@v3
    - name: Cache Gradle
      uses: actions/cache@v6
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', '**/gradle.properties', 'gradle/wrapper/gradle-wrapper.properties', 'gradle/libs.versions.toml') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Execute tests
      run: nix develop --command ./gradlew test
